In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [2]:
data={"color":["Red","Green","yellow","orange","pink"]}
df=pd.DataFrame(data)
df

    color
0     Red
1   Green
2  yellow
3  orange
4    pink

In [3]:
label_encoder=LabelEncoder()
df['Color_label']=label_encoder.fit_transform(df['color'])
df.head()

    color  Color_label
0     Red            1
1   Green            0
2  yellow            4
3  orange            2
4    pink            3

In [7]:
one_hot_encoder = OneHotEncoder()
one_hot_encoded = one_hot_encoder.fit_transform(df[['Color_label']])
one_hot_encoded_df=pd.DataFrame(one_hot_encoded.toarray(),columns=one_hot_encoder.get_feature_names_out())
df=pd.concat([df,one_hot_encoded_df],axis=1)
df

,color,Color_label,Color_label_0,Color_label_1,Color_label_2,Color_label_3,Color_label_4
0,Red,1,0.0,1.0,0.0,0.0,0.0
1,Green,0,1.0,0.0,0.0,0.0,0.0
2,yellow,4,0.0,0.0,0.0,0.0,1.0
3,orange,2,0.0,0.0,1.0,0.0,0.0
4,pink,3,0.0,0.0,0.0,1.0,0.0